### ISSUE TITLE
2017061000: upgrade.php tries to use table before it is defined

### ISSUE THREAD

**Issue by agrowe** [Panopto/Moodle-2.0-plugin-for-Panopto#101]
On line 302 `panopto_data::delete_panopto_relation($oldcourse->moodleid, true);` tries to move a row into the `mdl_block_panopto_old_foldermap` table but that does not exist until you get to line 353.

We had to create the table manually before being able to progress with the upgrade. (which fails again, but I will open a new issue for that).

The table needs to be create first in the upgrade script before progressing.

**Comment by jmalmsten-panopto** [comment]
Thank you for reporting this, 

I will investigate this and have a fix out soon.

**Comment by sharpchi** [comment]
Yes, this failed for me too. Moved the `$oldfoldermaptable = new xmldb_table('block_panopto_old_foldermap');` section before the `foreach ($oldpanoptocourses as $oldcourse) {` loop to make it work.

**Comment by jmalmsten-panopto** [comment]
Hey, 

This should be fixed, I also tried to maintain the same version so you should both be able to retry installing through the UI. 

Joe M
