### ISSUE TITLE
Release notes for 2017061000

### ISSUE THREAD

**Issue by sharpchi** [Panopto/Moodle-2.0-plugin-for-Panopto#106]
I think you need to make explicit release notes for your upgrade to 2017061000 stating that the plugin can only be upgraded via the UI, and that the user doing the upgrade *also* needs to be an administrator on the panopto server (I can imagine that may not always be the case).

**Comment by aspark21** [comment]
both of those things are covered in https://support.panopto.com/articles/Documentation/Moodle-Plugin-Upgrade-2017-2017061000

**Comment by sharpchi** [comment]
It would be good to include that info with the plugin itself. It's really important.

**Comment by jmalmsten-panopto** [comment]
Hey Mark,

I think that the information on the support document in Panopto is enough. The document contains major steps that should not be missed and if that is not read the upgrade will most likely fail anyway.

To be clear this document itself is linked in the release notes with a request to read it before upgrading.

Thanks,
Joe M.
