### ISSUE TITLE
Migration doesn't move folders

### ISSUE THREAD

**Issue by aspark21** [Panopto/Moodle-2.0-plugin-for-Panopto#108]
So there is now a "Parent folder name" setting in which all of the course folders are meant to be generated in. 

I assumed that the migration with that setting set would move all of the existing folders accordingly as part of the re-provisionning step. I migrated two sites & it didn't for either.

**Comment by jmalmsten-panopto** [comment]
We may consider this feature in the future, I will close this issue and make a internal item for future consideration. 

Thank you for your input, it is appreciated!

Joe M.

**Comment by aspark21** [comment]
Just to clarify, if we did want to move them. Would moving them manually work or not?

Or should we be generating a new ID for this to occur & then move the videos around & delete the old folders?
