### ISSUE TITLE
Viewer, Creator and Publish permission is not revoked when a students and/or teachers unenrol from the course

### ISSUE THREAD

**Issue by chrodos** [Panopto/Moodle-2.0-plugin-for-Panopto#114]
We have Panopto block version 2017080100 installed in Moodle 3.1. When a student or teacher is unenrolled from the course, Viewer, Creator and Publish permission is not revoked from the panopto folder.

**Comment by jmalmsten-panopto** [comment]
Hi,

Syncing is now done when a user attempts to access a Panopto block through Moodle. Once the user logs into a course with a Panopto block the sync code should fire and they will be removed from any courses they were un-enrolled in.

Could you let us know if this solves your issue? We will investigate in the meantime. 

Thanks,
Joe M

**Comment by chrodos** [comment]
Hi Joe,

I am aware of the new panopto block functionality. We checked and while it works for adding users, when you delete a user from a course it remains in the panopto folder.

**Comment by jmalmsten-panopto** [comment]
Hi,

The syncing is now per-user, not per-course. That user would get synced again when they attempt to access any Panopto folder through Moodle. If your problem still persists could you please open up a support ticket with Panopto, they will be able to assist you further.

Thanks,
Joe M.

**Comment by chrodos** [comment]
Ok. I will do that. But consider these two scenarios (we tested them and this is what happens):
a) A student is enrolled in two courses
b) the student is unenrolled from one of the two courses
c) the student can only view in moodle one of the two courses (meaning that this user will never see the panopto block and trigger the sync)
d) if the student logs into panopto he will be able to see both courses

Scenario 2:
a) A student is enrolled in N courses
b) the student is completely deleted from moodle
c) the student remains in all panopto folders previously provisioned

**Comment by jmalmsten-panopto** [comment]
Thanks for bringing these scenarios to our attention,

I have opened an internal work item for our team to investigate this further.

- Joe M

**Comment by chrodos** [comment]
Thank you, Joe. You are right. Only scenario 2 is valid.

**Comment by hitteshahuja** [comment]
Scenario 2 is a good use case as it would take care of archiving process common at most universities

**Comment by jmalmsten-panopto** [comment]
Hey,

I would try upgrading to 2017082900, it just got released. The issue should be taken care of there. unenrolment should fire a sync event, and when you delete a user it unenrols them from every course before deletion.

Thanks,
Joe M
