### ISSUE TITLE
Provisioning on new courses not working in latest release.

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#115]
In our 3.3.1 environment the new course creation isn't being provisioned.  Our error log is outputting this:

2017/08/10 14:40:24 [error] 9190#9190: *6197 FastCGI sent in stderr: "PHP message: Array
(
    [SessionManagementServiceSet::SetExternalCourseAccessForRoles] => SoapFault Object
        (
            [message:protected] => An error occurred deserializing the message. See server logs for details
            [string:Exception:private] => 
            [code:protected] => 0
            [file:protected] => /var/www/moodle/blocks/panopto/lib/SessionManagement/Set/SessionManagementServiceSet.php
            [line:protected] => 51
            [trace:Exception:private] => Array
                (
                    [0] => Array
                        (
                            [file] => /var/www/moodle/blocks/panopto/lib/SessionManagement/Set/SessionManagementServiceSet.php
                            [line] => 51
                            [function] => __call
                            [class] => SoapClient
                            [type] => ->
                            [args] => Array
                                (
                                    [0] => SetExter" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: localhost, request: "POST /course/edit.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "xxxxxxxxxx", referrer: "xxxxxxxxxxxxx/course/edit.php?category=65&returnto=catmanage"

**Comment by Syxton** [comment]
We are running the latest Panopto block release

**Comment by Syxton** [comment]
@hohno-panopto Sorry to tag you on this, just wanted to know if anyone else is having this issue.

**Comment by hohno-panopto** [comment]
@Syxton Thank you for the report and I am sorry for the delayed response. Somehow, this issue did not trigger email notification to me until you ping me again now.
I have not heard the same failure from anyone else so far.
We'll look into this problem.

**Comment by jmalmsten-panopto** [comment]
Hey,

This is an issue I have not seen yet, could you open a ticket with Panopto support so we can assist you further?

Thanks,
Joe

**Comment by Syxton** [comment]
@jmalmsten-panopto just an fyi this is now Case Number 00390801

**Comment by jmalmsten-panopto** [comment]
Hey,

I would try upgrading to 2017082900, it just got released. The issue should be taken care of there.

Thanks,
Joe M
