### ISSUE TITLE
UPGRADE BLOCKED when upgrading from 2017032000 to 2017082900

### ISSUE THREAD

**Issue by raad** [Panopto/Moodle-2.0-plugin-for-Panopto#118]
When upgrading from release 2017032000 to 2017082900 using the Moodle "admin" user, the system displays an error message:

> Panopto ClientData(old) to Public API(new) Upgrade Error - Lacking Folder Access
> UPGRADE BLOCKED: The user MoodleFUNC\admin does not have access to a provisioned Panopto course folder. Upgrading user must have at least viewer access to all Panopto course folders. It is highly reccommended that the upgrading user is an Administrator on Panopto

Within Panopto we have changed the system role of the MoodleFUNC\admin user to an Administrator, but this did not make any difference.

**Comment by hohno-panopto** [comment]
I am sorry for the trouble. Please contact support@panopto.com for further troubleshooting.

**Comment by hitteshahuja** [comment]
Same here. The only way to get around is to do a UI upgrade

**Comment by hohno-panopto** [comment]
@hitteshahuja, Please contact support@panopto.com We should be able to unblock you.

**Comment by jmalmsten-panopto** [comment]
Is this specific issue still a problem or was support able to help?

**Comment by jmalmsten-panopto** [comment]
Closing as fixed, please open a ticket with Panopto support if you experience more issues or need any other assistance.

**Comment by raad** [comment]
I can confirm the advice from support has enabled us to resolve the issue.
It seems that if you have entries in your panopto_folders table that have different providers, this will trigger the problem. In our case, we had refreshed our Test instance with data from our Live instance, but not realised this was an issue, so we had a mixture of Live and Test providers.
Removing the entries with the Live provider fixed the issue.
