### ISSUE TITLE
Issue with folder upgrading in 2017110600

### ISSUE THREAD

**Issue by agrowe** [Panopto/Moodle-2.0-plugin-for-Panopto#122]
Hi Panopto,

Previously we worked with Panopto support to allow the folder remapping function to be able to be run on the command line during the site upgrade.

In the new version, this functionality has been removed which makes it harder again to upgrade. Even though the process has been moved to a different script, it's still a web process that can take hours.

The max time limit is set to be 2 hours, but on our dev instance with half the amount of courses it was roughly an hour which is cutting it too fine.

This will also use up PHP web processes rather than a command line process which would be the preferred approach.

As our servers run in a load balanced environment, we would need to update the load balancer configurations to allow this single script to run for hours and change it back.

Can you please include a CLI version of the script at least, or a task that is able to be run on demand?

**Comment by jmalmsten-panopto** [comment]
Hi agrowe,

This is the same process as the 2017061000 upgrade. This process should only need to be run once, so if you already successfully upgraded through the CLI then this upgrade button is not necessary for you and you can completely ignore this release. If this does not make sense please open a ticket with Panopto support so our support team may discuss this issue directly with you over the phone. 

Thanks, 
Joe M

**Comment by agrowe** [comment]
Hi Joe,

We tested the upgrade on our dev instance but not on any of our prod instances. I will have to reach out to support to get this resolved.

Thanks
Alex

**Comment by jmalmsten-panopto** [comment]
Hi,

We just released a version of the block with a cli upgrade tool, please see the release notes for more information.

Thanks,
Joe M
