### ISSUE TITLE
Add ability to set a default folder to use & a way to bulk change the mapped folder

### ISSUE THREAD

**Issue by aspark21** [Panopto/Moodle-2.0-plugin-for-Panopto#123]
During a support call last week, I was introduced to the ability to map all courses of a moodle site to one panopto folder manually (create folder in panopto, add block in moodle & select the folder from the dropdown and repeat). This delivers our use case perfectly & have just done that manually for one of smaller sites.

However, this site had less than 100 courses & I now need to do this for one with 1200 courses - this is going to take weeks to achieve manually. Could you implement a way for this to be changed in bulk? either via cli or web interface of the plugin.

Also looking forward, we'd want all newly created / rolled over courses to be set to be mapped to that particular Panopto folder- could you add a site setting for this?
For disambiguation, this is about mapping to one specific folder rather than using a parent folder in which the course folders are created (which is already implemented).

I will also create a Support Case for this.

**Comment by hohno-panopto** [comment]
Please continue to use our support channel to discuss your specific requirement. Thanks!
