### ISSUE TITLE
Fatal error: Class 'SoapClient' not found in /blocks/panopto/lib/panopto_auth_soap_client.php on line 38

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Moodle-2.0-plugin-for-Panopto#126]
Although only a recommendation by Moodle  missing soap extension for php when doing a fresh install comes up with the above error ( only if debugging is enabled, otherwise a blank page is shown) . I do appreciate that panopto lib uses Soap to contact to the server but maybe you could allow the user to install the plugin and then show the error when setting up the plugin at a later stage.

**Comment by jmalmsten-panopto** [comment]
Hi @hitteshahuja,
 
Apologies for the delayed response. I have filed an internal work item to track this issue, the reference number for the internal work item is 100162. If you require future support please feel free to open a support ticket at [support.panopto.com](https:\\support.panopto.com).

Thanks,
Joe Malmsten

**Comment by zeroAps** [comment]
This should be resolved. Closing this issue.
