### ISSUE TITLE
Error when configuring Panopto block with login as

### ISSUE THREAD

**Issue by haietza** [Panopto/Moodle-2.0-plugin-for-Panopto#134]
When attempting to configure the Panopto block logged in as admin but using login as a teacher in their course with the Panopto block already provisioned, the following error is output:

PHP Notice:  Array to string conversion in .../moodledata/localcache/.../__Mustache_XXXX.php

The server error logs have a lot of output referencing these two files:
blocks/panopto/lib/SessionManagement/Get/SessionManagementServiceGet.php:203
blocks/panopto/lib/panopto_session_soap_client.php:325

Looks like there is an issue with the session/authentication between Moodle and Panopto when using login as, but since login as is used quite often for admins troubleshooting teacher issues, implementation of this should exist. Thanks for reviewing!

**Comment by hohno-panopto** [comment]
Hi, thank you for posting your issue and I am sorry for the trouble.
Please contact Panopto support about this issue, so that we may work closely together with you to solve this problem.
