### ISSUE TITLE
Provision course only with Panopto block

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#136]
On the setting: 
Currently it is either Yes, or No, but I would love to see a 3rd option which would be, "On panopto block view"

Basically, like enrollment, it only creates a course folder on panopto if the panopto block is added.

**Comment by jmalmsten-panopto** [comment]
Hi,

This should be resolved with the latest release of the Panopto block.

Thanks,
Joe
