### ISSUE TITLE
!!! Exception - Too few arguments to function panopto_category_data

### ISSUE THREAD

**Issue by Richardvi** [Panopto/Moodle-2.0-plugin-for-Panopto#143]
My cron file shows this:

Execute adhoc task: block_panopto\task\ensure_category
... started 15:47:09. Current memory use 18.9MB.
!!! Exception - Too few arguments to function panopto_category_data::__construct(), 1 passed in [dirroot]/blocks/panopto/classes/task/ensure_category.php on line 56 and exactly 3 expected !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 84 of /blocks/panopto/lib/panopto_category_data.php: ArgumentCountError thrown
* line 56 of /blocks/panopto/classes/task/ensure_category.php: call to panopto_category_data-&gt;__construct()
* line 185 of /lib/cronlib.php: call to block_panopto\task\ensure_category-&gt;execute()
* line 74 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 61 of /admin/cli/cron.php: call to cron_run()  !!
<br />
<b>Fatal error</b>:  Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
/home/learn/public_html/lib/classes/task/manager.php on line 461

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory-&gt;get_lock(Resource id #1354);  $lock-&gt;release();  // Locks must ALWAYS be released like this.

 in /home/learn/public_html/lib/classes/lock/lock.php:117
Stack trace:
#0 [internal function]: core\lock\lock-&gt;__destruct()
#1 {main}
  thrown in <b>/home/learn/public_html/lib/classes/lock/lock.php</b> on line <b>117</b><br />

---------

I have experienced errors when creating courses, creating categories in Moodle 3.5

Right now Panopto is seriously messing up my Moodle installation. I tried to uninstall it, but then I got many of these errors:

Adhoc task complete: block_panopto\task\sync_user_login
Execute adhoc task: block_panopto\task\sync_user_login
... started 17:34:02. Current memory use 27.7MB.
... used 46 dbqueries
... used 0.4519031047821 seconds
Adhoc task complete: block_panopto\task\sync_user_login
!!! The operation timed out while waiting for a lock. !!!
!! 
Error code: locktimeout !!
!! Stack trace: * line 452 of /lib/classes/task/manager.php: moodle_exception thrown
* line 73 of /lib/cronlib.php: call to core\task\manager::get_next_adhoc_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
 !!

-----------------

We are NOT using the Panopto block in our courses (we don't use blocks at all in Moodle). But still we do want our user data, course data and category data to be synchronised woth Panopto.

It seems our many users, courses and categories in Moodle messes this proces up.

Is there someway to get this working with BIG Moodle installations?

**Comment by jmalmsten-panopto** [comment]
I believe the latest beta release of the Panopto block should clear up the category issues.

I am guessing the lock and other adhoc issues are because async tasks are failing from the category issues.

If you still wish to uninstall the block I would suggest clearing all Panopto adhoc tasks from the Moodle environment before doing so.  I would suggest running the cli script in the lib/cli/remove_all_panopto_adhoc_tasks.php. You should not have any category issues if you update to the new block (already queued adhoc tasks MAY experience the issue, bot not any queued from the updated block).

If you have any further issues please open a support ticket with Panopto.

Thanks,
Joe

**Comment by Richardvi** [comment]
Thanks, Panopto has helped me a lot with this. Most problems are solved, only one left: we have to many courses to synchronize to Panopto. This can not be done using the gui, it will take forever. I would really need a cli-script for this so it runs better. I have requested this at Panopto already, hope they can make this!
Thanks again, Richard.
