### ISSUE TITLE
Request: add user first and lastname to personal folder

### ISSUE THREAD

**Issue by Richardvi** [Panopto/Moodle-2.0-plugin-for-Panopto#146]
When a user logs into Moodle for the first time, a personal folder is being created in Panopto. This personal folder has this syntax: **moodleinstancename\moodleusername**

This makes it sometimes pretty difficult to find the folder for our scheduling & planning department that has to look up the username of a teacher for making scheduled recordings to that folder.

Is it possible to somehow add the first and last name to the personal user folder? For example this syntax:  **moodleinstancename\moodleusername (firstname lastname)**

That way the folder is more easy to find.

**Comment by hohno-panopto** [comment]
Thank you for the feedback. This is not something Moodle plug-in may do at this time. We are going to consider adding this feature as core Panopto server feature.
