### ISSUE TITLE
The plugin does not pick up new courses or course copies done through the API

### ISSUE THREAD

**Issue by bendec** [Panopto/Moodle-2.0-plugin-for-Panopto#151]
When we use the api to copy courses every academic year (7000 courses) the Panopto plugin does not pick up these actions. So no provisioning and no adding to the mdl_block_panopto_importmap table.

**Comment by hohno-panopto** [comment]
I am sorry to respond this entry. As you know, we are working together on your problem via support channel. We do not need this Issue entry at this time.
