### ISSUE TITLE
consider adding travis-ci support

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#154]
Some of the tests run by the Moodle.org plugins db can be run via travis-ci on each commit in your github repo. Enabling Travis integration helps you to make sure future changes to your plugin will continue to follow the guidelines.

See the code prechecks report in the moodle.org plugins db here:
https://moodle.org/plugins/pluginversion.php?id=20742

More information on this travis ci support is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/YOUR_GITHUB_USERNAME
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
global:

MOODLE_BRANCH=MOODLE_35_STABLE
you might want to add other branches to that list - so you might want to change it something like:

env:
global:
MOODLE_BRANCH=MOODLE_35_STABLE
MOODLE_BRANCH=MOODLE_36_STABLE
MOODLE_BRANCH=MOODLE_37_STABLE

**Comment by jmalmsten-panopto** [comment]
Hi @danmarsden,
 
Apologies for the delayed response. I have filed an internal work item to track this issue, the reference number for the internal work item is 91222. If you require future support please feel free to open a support ticket at [support.panopto.com](https://support.panopto.com).

Thanks,
Joe Malmsten

**Comment by danmarsden** [comment]
fyi... since this was created travis.org has been deprecated and the only way to use travis-ci is via a paid plan on their .com site .... people are moving to using github actions instead(which is free). unfortunately not a lot of documentation on using this yet, but we have a couple of templates here you might find useful:

https://github.com/catalyst/moodle-auth_saml2/blob/master/.github/workflows/38-master.yml
https://github.com/catalyst/moodle-local_envbar/blob/VERSION2/.github/workflows/ci.yml

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release, we have added Github actions to the plug-in.

Thanks,
Joe
