### ISSUE TITLE
IDE Config files should not be in git.

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#155]
nbproject/private has been accidentally included in the github repository by a developer - it contains IDE specific files that shouldn't be in your codebase - can you please remove it?

thanks!

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
