### ISSUE TITLE
Incorrect camel case used in lang strings

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#156]
Moodle uses sentence case - quite a few of your lang strings use camel case - for example:?

$string['begin_reinitializing_imports'] = 'Begin Reinitializing Imports';
$string['block_global_application_key'] = 'Application Key';

Should be more like:
$string['begin_reinitializing_imports'] = 'Begin reinitializing imports';
$string['block_global_application_key'] = 'Application key';

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
