### ISSUE TITLE
classes and in-line code should not be mixed

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#157]
files like build_category_structure.php and panopto_course.php contain a mix of in-line code and classes.

Classes should be defined in their own stand-alone file and preferably in the classes folder rather than mixed in with in-line code.

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
