### ISSUE TITLE
please use curly braces instead of $CFG->prefix

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#158]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/master/lib/panopto_category_data.php#L322

should really be:
SELECT id,depth FROM {course_categories} WHERE id NOT IN (SELECT parent FROM {course_categories})

(probably just old code that hasn't been updated!) :-)

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
