### ISSUE TITLE
plugin code contains some external classes but the licensing of these files is not clear

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#159]
quite a few of the files in the lib folder appear to be external libraries included in the project, but the license information on these files and their origin is not clear.

Ideally stuff like your SessionManagement classes (if owned by Panopto) should be updated to state the license these files are released under.

But - what is also really important is that you include information about these in a 3rd party libs file as defined here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

Note, the above is actually a requirement for all plugins in the moodle.org plugins db and having this file missing when you include 3rd party libs would block approval in the plugins db.

One of the helpful side-effects of having that file in place is that moodle's coding guideline checks exclude these files when running travis and when running in the moodle.org plugins db.

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
