### ISSUE TITLE
namespacing violations

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#160]
Moodle has some clear rules around function and class names.
functions like "is_null_or_empty_string" and "is_guid_empty" do not follow these guidelines.
it would be good for you to review these docs:
https://docs.moodle.org/dev/Coding_style#Naming_Conventions

This is also something that would usually block approval in the plugins db.

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues,
Joe
