### ISSUE TITLE
please use Moodle's curl wrapper instead of calling curl directly.

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-2.0-plugin-for-Panopto#161]
Many Moodle servers sit behind a web proxy, the internal Moodle "Curl" class deals with this and should be used instead of making calls to curl_init() directly.

**Comment by jmalmsten-panopto** [comment]
Hey Dan,

This should be resolved in the 2020072700 release. 

Thanks again for bringing this to our attention and let me know if you see any other issues. 

- Joe
