### ISSUE TITLE
Panopto AJAX call not respecting course forced language.

### ISSUE THREAD

**Issue by t6nis** [Panopto/Moodle-2.0-plugin-for-Panopto#162]
Noticed that when my dashboard language is DE and i force some course language to be EN then panopto block will still render the answer in DE.

So require_login() in panopto_content.php should have $course parameter passed with it.
Instead: 
```
try {
    require_login();
    require_sesskey();
    header('Content-Type: text/html; charset=utf-8');
    global $CFG, $USER;

    $courseid = required_param('courseid', PARAM_INT);

    $content = new stdClass;
```

IT should be something like this:
```
try {
    $courseid = required_param('courseid', PARAM_INT);
    $course = $DB->get_record('course', array('id' => $courseid), '*', MUST_EXIST);
    require_login($course);
    require_sesskey();
    header('Content-Type: text/html; charset=utf-8');
    global $CFG, $USER;
    
    $content = new stdClass;
```

I hope this helps!

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for bringing this to our attention. We have made an internal work item for this issue and will look into it at a future release. 

Thanks,
Joe

**Comment by jmalmsten-panopto** [comment]
Hi,

This should be resolved with the latest release of the Panopto block.

Thanks,
Joe
