### ISSUE TITLE
Old server settings in mdl_block_panopto_foldermap

### ISSUE THREAD

**Issue by dsoini** [Panopto/Moodle-2.0-plugin-for-Panopto#163]
The database table mdl_block_panopto_foldermap has a lot of old servernames and app keys after we moved our system to a different server. It seems that changing the settings didn't update the table. We are trying to use the panoptobutton plugin for atto and it runs into these old settings and causes activities (LTI activities at least) not to be able to be added to the page. The error traces to this table even though the error is in a different panopto plugin, and it doesn't seem like it should be the job of an atto editor button to clean up this table. I will post this error over on the panoptobutton repo as well.

**Comment by jmalmsten-panopto** [comment]
Hi,

If there is an issue that happened after the server move we would need to have Panopto support look at this. To have Panopto assist you with this issue please open a Panopto support ticket at [https://support.panopto.com](https://support.panopto.com).

Thanks,
Joe
