### ISSUE TITLE
Ajax call should not hold session lock.

### ISSUE THREAD

**Issue by andrewmadden** [Panopto/Moodle-2.0-plugin-for-Panopto#168]
In `/panopto_content.php`, close the session so that the users other tabs in the same session are not blocked.

At scale, some clients were reporting that end users were receiving 500 errors. We discovered that it was due to an Ajax request failing to make a connection to a remote Panopto server and timing out. 

A session lock is not required for the external Ajax request.

**Comment by agrowe** [comment]
Moodle 3.9 also had read only sessions now available for this kind of thing.

https://docs.moodle.org/310/en/Session_handling#Read_only_sessions

Adding `define('READ_ONLY_SESSION', true);` here would do it

https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/32168b868446504e60f4f730fead7194b893ebfd/panopto_content.php#L25

**Comment by jmalmsten-panopto** [comment]
Hi,

This should be resolved with the latest release of the Panopto block.

I will file an internal work item to look into adding the define in the future. 

Thanks,
Joe
