### ISSUE TITLE
Move AJAX health check to be intermittent to prevent spamming endpoint, and locking up Moodle session.

### ISSUE THREAD

**Issue by andrewmadden** [Panopto/Moodle-2.0-plugin-for-Panopto#170]
Modify `lib/panopto_data.php:is_server_alive` to keep track of last health check and when the next health check should be requested.

At scale, some clients were reporting that end users were receiving 500 errors. We discovered that it was due to an Ajax request failing to make a connection to a remote Panopto server and timing out.

Instead of all students needing to make the request to check the health of the remote server, the health check can be made periodically (30 seconds by default), and the result cached in Moodle and used by all other users for that period.

**Comment by jmalmsten-panopto** [comment]
Hi @andrewmadden,
 
Apologies for the delayed response. I have filed an internal work item to track this issue, the reference number for the internal work item is 100171. If you require future support please feel free to open a support ticket at [support.panopto.com](https://support.panopto.com).

Thanks,
Joe Malmsten

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be resolved as of the 2021062900 release a while back. I am going to close this issue for now.

Thanks,
Joe Malmsten
