### ISSUE TITLE
Deny multiple instances on a page

### ISSUE THREAD

**Issue by A0B** [Panopto/Moodle-2.0-plugin-for-Panopto#175]
Hi !

Your Javascript takes into account the only first bloc _block_panopto_ on a page. 

Thus please considere to not allow more than one instance of the bloc on the same page.
You could achieve this by adding the standart function _instance_allow_multiple()_ into _block_panopto.php_:

```
    /**
     * allow more than one instance of the block on a page
     *
     * @return boolean
     */
    public function instance_allow_multiple() {
        return false;
    }
```

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be handled with the latest release. 

Thanks,
Joe
