### ISSUE TITLE
Fresh installation "XML database file errors found"

### ISSUE THREAD

**Issue by ni-ght** [Panopto/Moodle-2.0-plugin-for-Panopto#179]
When performing a fresh installation on Moodle 3.9, "block_panopto" version "2021062900", I get:

```
block_panopto
XML database file errors found

More information about this error

×Debug info: Errors found in XMLDB file: Problem loading table block_panopto_importmap, Some INDEXES name values are incorrect
Error code: ddlxmlfileerror

×Stack trace:
line 354 of /lib/ddl/database_manager.php: ddl_exception thrown
line 370 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 1030 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 567 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
line 713 of /admin/index.php: call to upgrade_noncore()
```

Actually, "db/install.xml" seems to have two indices with the same name "import_moodle_id".

Many thanks.

**Comment by Limekiller** [comment]
Yep, this is a major issue. I submitted a pull request for it here: #180 
Hopefully it gets approved and merged.

**Comment by jmalmsten-panopto** [comment]
Hi,

We have identified the issue and are working to verify the fix. We are planning on releasing an updated version of the plugin soon. If you need further assistance please open a support ticket with Panopto at https://support.panopto.com.

Thanks,
Joe Malmsten

**Comment by jmalmsten-panopto** [comment]
Hi,

Closing this issue as it should be fixed with the latest release. If you have any other issues please contact Panopto support. 

Thanks,
Joe Malmsten

**Comment by ni-ght** [comment]
Many Thanks
