### ISSUE TITLE
panopto_content.php could / should be a readonly session

### ISSUE THREAD

**Issue by dmitriim** [Panopto/Moodle-2.0-plugin-for-Panopto#188]
Since 3.9 Moodle allows pages to declare READ_ONLY_SESSION. See https://docs.moodle.org/311/en/Session_handling#Read_only_sessions for more datails.

It feels like panopto_content.php could / should declare read only sessions.

**Comment by jmalmsten-panopto** [comment]
Hi, 

I have filed an internal work item for this issue, we will take a look at it sometime in the future. 

Thanks,
Joe Malmsten
