### ISSUE TITLE
SessionManagementWsdlClass.php __set_state doesn't adhere the php 8.0 method signature

### ISSUE THREAD

**Issue by okigye** [Panopto/Moodle-2.0-plugin-for-Panopto#190]
Hello! 
 
In 
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/9a859fc7a0b2f72079f62a1feedd831a5fba171a/lib/SessionManagement/SessionManagementWsdlClass.php#L256
the signature of the SessionManagementWsdlClass's  __set_state function is 
(array $_array,$_className = __CLASS__)
which doesn't matches the signature 
public function __set_state(array $properties): object {} 
This causes fatal error.
See php documentation: https://php.watch/versions/8.0/magic-method-signatures

Thanks for your help.
Okigye
Ps. I'm sorry if i'm sounding rude, or terse, English isn't my first language.

**Comment by jrchamp** [comment]
Looks like this was fixed 15 days ago.

**Comment by jmalmsten-panopto** [comment]
Yes, this issue was fixed with the last release. I will be closing this ticket now!

Thank you for your patience, 
Joe Malmsten
