### ISSUE TITLE
CFG was missing

### ISSUE THREAD

**Issue by klasuk** [Panopto/Moodle-2.0-plugin-for-Panopto#194]
I got an error:

Notice: Undefined variable: CFG in [MOODLEPATH]/blocks/panopto/lib/panopto_data.php on line 26
Notice: Trying to get property 'libdir' of non-object in [MOODLEPATH]/blocks/panopto/lib/panopto_data.php on line 26

Plugin version is 2022122000

I guess there should be "global $CFG" before require_once ?

**Comment by jmalmsten-panopto** [comment]
Hi,

We have filed an internal work item to handle this issue. 

Could you please tell me what version of Moodle you are using and what reproduction steps you take to reproduce this issue? 

Thanks,
Joe

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be resolved in the latest beta release.

Thanks,
Joe
