### ISSUE TITLE
Error when upgrade to moodle 4.1

### ISSUE THREAD

**Issue by qqtuyen** [Panopto/Moodle-2.0-plugin-for-Panopto#200]
PHP 8.0.28 (cli) (built: Feb 14 2023 18:32:57) ( NTS )

sudo -u www-data php admin/cli/mysql_collation.php  --collation=utf8mb4_unicode_ci
Converting tables and columns to 'utf8mb4_unicode_ci' 
Converted: 0, skipped: 3260, errors: 0

// Initialize $plugin object if it hasn't been already.
$plugin = (isset($plugin) ? $plugin : new stdClass());

// Plugin version should normally be the same as the internal version.
// If an admin wants to install with an older version number, however, set that here.
$plugin->version = 2023031400;

// Requires this Moodle version - 2.7.
$plugin->requires = 2014051200;
$plugin->cron = 0;
$plugin->component = 'block_panopto';
$plugin->maturity = MATURITY_STABLE;
$plugin->dependencies = array(
    'mod_forum' => ANY_VERSION
);
/* End of file version.php */

sudo -u www-data php admin/cli/upgrade.php --non-interactive
-->block_panopto
Default exception handler: DDL sql execution error Debug: Table 'mdl_block_panopto_foldermap' already exists
CREATE TABLE mdl_block_panopto_foldermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodleid BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_app_key VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    publisher_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '1',
    creator_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '3,4',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanofold_moo2_ix (moodleid)
, KEY mdl_blocpanofold_pan2_ix (panopto_server)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to Panopto folders'
;
CREATE TABLE mdl_block_panopto_importmap (
    id BIGINT(10) NOT NULL auto_increment,
    target_moodle_id BIGINT(10) NOT NULL,
    import_moodle_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanoimpo_tar2_ix (target_moodle_id)
, KEY mdl_blocpanoimpo_imp2_ix (import_moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to imported courses'
;
CREATE TABLE mdl_block_panopto_creatormap (
    id BIGINT(10) NOT NULL auto_increment,
    moodle_id BIGINT(10) NOT NULL,
    role_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanocrea_moo2_ix (moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='a table that maps Moodle roles to the creator capability whe'
;
CREATE TABLE mdl_block_panopto_publishermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodle_id BIGINT(10) NOT NULL,
    role_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanopubl_moo2_ix (moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='a table that maps Moodle roles to the publisher capability w'
;
CREATE TABLE mdl_block_panopto_old_foldermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodleid BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_app_key VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    publisher_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '1',
    creator_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '3,4',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanooldfold_moo2_ix (moodleid)
, KEY mdl_blocpanooldfold_pan2_ix (panopto_server)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to inactive ClientData style Panopto fold'
;
CREATE TABLE mdl_block_panopto_categorymap (
    id BIGINT(10) NOT NULL auto_increment,
    category_id BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanocate_cat2_ix (category_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='A list of mapped category folders in Panopto'
Error code: ddlexecuteerror
* line 500 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1103 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
* line 427 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
* line 372 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
* line 1083 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
* line 679 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! DDL sql execution error !!!
!! Table 'mdl_block_panopto_foldermap' already exists
CREATE TABLE mdl_block_panopto_foldermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodleid BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_app_key VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    publisher_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '1',
    creator_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '3,4',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanofold_moo2_ix (moodleid)
, KEY mdl_blocpanofold_pan2_ix (panopto_server)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to Panopto folders'
;
CREATE TABLE mdl_block_panopto_importmap (
    id BIGINT(10) NOT NULL auto_increment,
    target_moodle_id BIGINT(10) NOT NULL,
    import_moodle_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanoimpo_tar2_ix (target_moodle_id)
, KEY mdl_blocpanoimpo_imp2_ix (import_moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to imported courses'
;
CREATE TABLE mdl_block_panopto_creatormap (
    id BIGINT(10) NOT NULL auto_increment,
    moodle_id BIGINT(10) NOT NULL,
    role_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanocrea_moo2_ix (moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='a table that maps Moodle roles to the creator capability whe'
;
CREATE TABLE mdl_block_panopto_publishermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodle_id BIGINT(10) NOT NULL,
    role_id BIGINT(10) NOT NULL,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanopubl_moo2_ix (moodle_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='a table that maps Moodle roles to the publisher capability w'
;
CREATE TABLE mdl_block_panopto_old_foldermap (
    id BIGINT(10) NOT NULL auto_increment,
    moodleid BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_app_key VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    publisher_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '1',
    creator_mapping VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT '3,4',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanooldfold_moo2_ix (moodleid)
, KEY mdl_blocpanooldfold_pan2_ix (panopto_server)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='Map Moodle courses to inactive ClientData style Panopto fold'
;
CREATE TABLE mdl_block_panopto_categorymap (
    id BIGINT(10) NOT NULL auto_increment,
    category_id BIGINT(10) NOT NULL,
    panopto_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    panopto_server VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_blocpanocate_cat2_ix (category_id)
)
 ENGINE = InnoDB
 DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
 COMMENT='A list of mapped category folders in Panopto'
Error code: ddlexecuteerror !!
!! Stack trace: * line 500 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database-&gt;query_end()
* line 1103 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database-&gt;query_end()
* line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database-&gt;change_database_structure()
* line 427 of /lib/ddl/database_manager.php: call to database_manager-&gt;execute_sql_arr()
* line 372 of /lib/ddl/database_manager.php: call to database_manager-&gt;install_from_xmldb_structure()
* line 1083 of /lib/upgradelib.php: call to database_manager-&gt;install_from_xmldb_file()
* line 679 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!

**Comment by jmalmsten-panopto** [comment]
Hi,

To be able to properly assist you with this issue we will need you or your support contact to please open a support ticket at [support.panopto.com](https://support.panopto.com).

Thanks,
Joe Malmsten

**Comment by zeroAps** [comment]
Closing this for now, and if needed support ticket can still be open to investigate this. Thanks
