### ISSUE TITLE
Add Panopto-button to new TinyMCE

### ISSUE THREAD

**Issue by Richardvi** [Panopto/Moodle-2.0-plugin-for-Panopto#203]
We are migrating from Atto to TinyMCE and we need the Panopto button to be present in TinyMCE.

Please note that this once was available in TinyMCE legacy. In Moodle 4.2, the new TinyMCE will be the standard and Atto will be gone.

**Comment by zeroAps** [comment]
We made a new plugin that is available [here](https://github.com/Panopto/moodle-tiny_panoptoltibutton/releases). You're free to use it and test, it's the first version so any feedback is welcome.

**Comment by Richardvi** [comment]
I'm testing it now, but we don't have Panopto set up for LTI. It's not necessary, at least until now it wasn't. All users are synchronized upon login. Why do we need the LTI? For Atto we also didn't need LTI to set up.

If it needs to be setup, I will take a look at it. But for now I don't really understand why this is needed?

**Comment by zeroAps** [comment]
The new Tiny plugin we have created for Moodle 4.2 is LTI, and in order to use it, we need LTI tool configured. The old TinyMCE plugin was not LTI based, so you could use it without the LTI tool configured.

**Comment by zeroAps** [comment]
Sounds good. Since it is first version, feedback is highly appreciate so if you have time sometime you can just let us know the issues and we will work through them sometimes. Thank you.

**Comment by zeroAps** [comment]
We have released new plugin, we can close this.
