### ISSUE TITLE
Tiny typo

### ISSUE THREAD

**Issue by klasuk** [Panopto/Moodle-2.0-plugin-for-Panopto#208]
Please fix this tiny typo:
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/3b63cdb11dce9129a2e6b45af081332aac68f25d/settings.php#L38

Pre-increment did not work with php 7.4

**Comment by zeroAps** [comment]
Hi,

I have filed an internal work item to look into this issue.

Thank you for reporting,
Adis

**Comment by zeroAps** [comment]
We have release new plugin, we can close this.
