### ISSUE TITLE
Adhoc task failed: block_panopto\task\sync_user,Undefined constant "STDOUT"

### ISSUE THREAD

**Issue by Richardvi** [Panopto/Moodle-2.0-plugin-for-Panopto#210]
I reported this before, the error went away and now is back:

_Execute adhoc task: block_panopto\task\sync_user
Adhoc task id: 1174141
Adhoc task custom data: {"courseid":"27946","userid":"25263"}
... started 01:21:25. Current memory use 41.6 MB.
... used 19 dbqueries
... used 0.36937999725342 seconds
Adhoc task failed: block_panopto\task\sync_user,Undefined constant "STDOUT"_

Is there anything I can do to make sure this runs OK? Or is there anything Panopto can do to run this differently?

Moodle 4.3.2

**Comment by zeroAps** [comment]
Is this still happening? Can you create support ticket with more details so we can investigate properly. Thanks a lot.

**Comment by Richardvi** [comment]
Not right now. It appears every now and then, doesn't seem to cause issues. I don't really understand what extra info I could provide on this error.

**Comment by zeroAps** [comment]
If it happens again, you can create support ticket and we will try to investigate issue. Closing this for now. Thanks.
