### ISSUE TITLE
Deprecated use of dynamic properties - showing in error log / cron

### ISSUE THREAD

**Issue by jrchamp** [Panopto/Moodle-2.0-plugin-for-Panopto#213]
Use of implicit dynamic properties was deprecated by PHP in November 2021. Options for fixing:

- Add the properties to the class definition (most common fix; may improve memory efficiency)
- Keep the variable local, fix the property name or delete it because it was not being used (cleans up code)
- Explicitly add the attribute which allows dynamic properties (this is rare; using stdClass instead is recommended)

`PHP Deprecated:  Creation of dynamic property panopto_category_data::$uname is deprecated in lib/panopto_category_data.php on line 107`
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/a05f8b6e3cf2dc1751c02a129fa33bbdd059cafd/lib/panopto_category_data.php#L102-L107
`PHP Deprecated:  Creation of dynamic property panopto_category_data::$sessiongroupid is deprecated in lib/panopto_category_data.php on line 112`
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/a05f8b6e3cf2dc1751c02a129fa33bbdd059cafd/lib/panopto_category_data.php#L109-L113
`PHP Deprecated:  Creation of dynamic property panopto_session_soap_client::$sessionmanagementserviceensure is deprecated in lib/panopto_session_soap_client.php on line 667`
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/a05f8b6e3cf2dc1751c02a129fa33bbdd059cafd/lib/panopto_session_soap_client.php#L666-L668

If you are open to a Pull Request, please let us know.

**Comment by zeroAps** [comment]
Thanks @jrchamp. We will create internal item to clean this up. Thanks.

**Comment by zeroAps** [comment]
We have cleaned this up in the latest release of the block. Closing this for now. Thank you.
