### ISSUE TITLE
Moodle 2.7

### ISSUE THREAD

**Issue by Vladimir7719** [Panopto/Moodle-2.0-plugin-for-Panopto#22]
After updating my moodle to ver 2.7 and installing panopto block I see this issue:
Warning: require_once(PanoptoSoapClient.php): failed to open stream: No such file or directory in /home/ctest475/public_html/blocks/panopto/lib/panopto_data.php on line 27

Fatal error: require_once(): Failed opening required 'PanoptoSoapClient.php' (include_path='/home/ctest475/public_html/lib/zend:/home/ctest475/public_html/lib/pear:.:/usr/local/php54/pear') in /home/ctest475/public_html/blocks/panopto/lib/panopto_data.php on line 27

how to fix it?

**Comment by Hiroshi-p** [comment]
We internally tested plug-in 2016081900 Release with Moodle 3.1 and this problem did not repro.
Please feel free to reopen this if anyone sees this problem with latest Moodle + latest plug-in.
