### ISSUE TITLE
contents of <head> moving inside <body> tag when editing course

### ISSUE THREAD

**Issue by ericbjellarl** [Panopto/Moodle-2.0-plugin-for-Panopto#24]
There appears to be an issue with this plugin which moves the contents of the <head> inside the body tag when editing a course. When the panopto plugin is uninstalled the issue is no longer present.

It seems the issue is related to the encoding of lib/block_panopto_lib.php and lib/PanoptoSoapClient.php.  They are currently UTF-8 with BOM. When these files are saved with UTF-8 encoding, the issue goes away. I'm not completely sure of the implications of this, but I believe using UTF-8 is recommended.

**Comment by Hiroshi-p** [comment]
We internally tested plug-in 2016081900 Release with Moodle 3.1 and this problem did not repro.
It is assumed to be fixed by one of commits between the issue was opened and right now.
Please feel free to reopen this if anyone sees this problem with latest Moodle + latest plug-in.
