### ISSUE TITLE
Error after block update

### ISSUE THREAD

**Issue by vickerylm** [Panopto/Moodle-2.0-plugin-for-Panopto#25]
When upgrading from a previous version of the panopto block, we get the following error when adding a new block (or accessing an existing). It appears the new column(s) are not added during the upgrade process.

Debug info: Unknown column 'panopto_server' in 'field list'
SELECT panopto_server FROM mdl_block_panopto_foldermap WHERE moodleid = ?
[array (
0 => '8',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1476 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
line 1549 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1530 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 1509 of /lib/dml/moodle_database.php: call to moodle_database->get_field_select()
line 218 of /blocks/panopto/lib/panopto_data.php: call to moodle_database->get_field()
line 52 of /blocks/panopto/lib/panopto_data.php: call to panopto_data::get_panopto_servername()
line 105 of /blocks/panopto/block_panopto.php: call to panopto_data->__construct()
line 294 of /blocks/moodleblock.class.php: call to block_panopto->get_content()
line 236 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 993 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1045 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 361 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 45 of /theme/asu/layout/columns3.php: call to core_renderer->standard_head_html()
line 877 of /lib/outputrenderers.php: call to include()
line 807 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()

**Comment by kabalin** [comment]
It is probably not of particular importance now, but changing to multiple servers support in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/09022548488f99984c584f63d614d51779200750 resulted in necessity to re-enter Panopto settings after block upgrade, when Moodle upgrade is run via commad line the reason why Panopto block has stopped working is not obvious. Ideally the patch should have come with a snippet in upgrade.php to re-define existing Panopto host/key settings as the "first server" and remove old variables from the config (abandoned settings block_panopto_server_name and block_panopto_application_key are still around though never used).

Also notice that abandoned settings are re-used in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/31e69d5d06f25b3d1f40f99e93b488b25027a362 upgrade patch, that landed several days after multiple server support became available to public. This might have caused issues for people who upgraded by that time and entered new muti-server settings that were different from original one they had, upgrade https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/31e69d5d06f25b3d1f40f99e93b488b25027a362 could just reset their hosts/keys in foldermap table to old values.

**Comment by Hiroshi-p** [comment]
I am sorry for responding to this issue super late.
We've added upgrade.php since then and this specific issue is not the current issue.
Let me close this entry.
