### ISSUE TITLE
New panopto block settings should be saved in mdl_config_plugins table

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Moodle-2.0-plugin-for-Panopto#26]
Right now the settings seems to be saved in mdl_config which is more of a global config area in Moodle. Since Panopto is a block it should be ideally saved in mdl_config_plugins table. 

More info : https://docs.moodle.org/dev/Blocks#Configure_That_Out

**Comment by kabalin** [comment]
@hitteshahuja I am sure you meant https://docs.moodle.org/dev/Blocks#The_Effects_of_Globalization ;)

**Comment by kabalin** [comment]
Fixed in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/df11c29fbb2355464e6d21bbded97f7388dd0441 The patch moves all global block configuration to plugin level and makes necessary changes to the way of accessing plugin level configuration values.

**Comment by Hiroshi-p** [comment]
Fixed by  https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/4572d44f3a612dd83854b10cc27a4f24b8483b6e
