### ISSUE TITLE
Error on attempt to add Panopto block to the new course.

### ISSUE THREAD

**Issue by kabalin** [Panopto/Moodle-2.0-plugin-for-Panopto#34]
Attempt to add a block to the new course results in the error:
```
Debug info: ERROR: invalid input syntax for integer: ""
SELECT * FROM mdl_role_capabilities WHERE contextid = $1 AND roleid = $2 AND capability = $3
[array (
0 => 28948,
1 => '',
2 => 'block/panopto:provision_aspublisher',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1476 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1448 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1427 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 1569 of /lib/accesslib.php: call to moodle_database->get_record()
line 308 of /blocks/panopto/block_panopto.php: call to assign_capability()
line 112 of /blocks/panopto/block_panopto.php: call to block_panopto->set_course_role_permissions()
line 294 of /blocks/moodleblock.class.php: call to block_panopto->get_content()
line 236 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 993 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1045 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 361 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 45 of /theme/clean/layout/columns3.php: call to core_renderer->standard_head_html()
line 877 of /lib/outputrenderers.php: call to include()
line 807 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()
```

I believe, this is a regression introduced in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/97755657b52a954d6c513fe5fcdbfe35b3d04e1a, it seems attempting to explode an empty string, that results in array with an empty element that is treated afterwards as role variable. 

**A polite note for integrator**: the merged commit https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/97755657b52a954d6c513fe5fcdbfe35b3d04e1a is adding a really good feature and I appreciate the amount of work a developer made, but it has many generic coding style issues such as wrong indents, inconsistency in control statements style, trailing spaces. Ideally, the contributed code should follow https://docs.moodle.org/dev/Coding_style, at least in the aspects of indent, wrapping and control statements - this would make a further work simpler and encourage contributors ;)

**Comment by kabalin** [comment]
Issue is fixed in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/8280baad0759ffd5493a25f0a360ffb630dbde16

**Comment by kabalin** [comment]
RE coding style, I sorted it all in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/447124e56841b22adfc2b7aec7316e73f65c367d

**Comment by Panopto** [comment]
Thank you so much for both fixes. And thank you also for the stylistic feedback, we commit to be more careful to follow the style guideline going forward.

So that I can reproduce the issue you report above, can you tell me the Panopto server version you are using?

We have set aside time next week to do tests against pull requests. We will evaluate these two fixes at that time as well for the main branch.

**Comment by kabalin** [comment]
Thanks. The version we are using is 4.7.0.18401, but the issue above is purely a bug in the plugin, no matter which Panopto version is in use.

**Comment by kabalin** [comment]
Just read about pull requests, feel free to merge everything you will see in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commits/master (or shall I create a pull request?), most recent fixes will be there. Just keep in mind if you end up cheery-picking commits, that style issues fix (https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/447124e56841b22adfc2b7aec7316e73f65c367d) needs to be applied first, as my other patches depend on it.

**Comment by Panopto** [comment]
Thanks for clarifying about the Panopto version. The Publisher role wasn't added to Panopto until version 4.8.0, so you may also run into additional issues with this specific change on that Panopto version. We did a fork for pre-4.8.0 servers so we don't reference the new role in that version.

**Comment by kabalin** [comment]
Could you please state which commit/release fixes this? Thanks.

**Comment by Panopto** [comment]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/f0aab3bd9fd30d3c8055b7cc72e7b9bf7e7a7753

**Comment by Panopto** [comment]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/c3c34a8f64132e57373fccaa501d3258ad704b7e
and
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/eb35d5d83c94bb1948232223d5f3dac6a2f0c39c
addressed these issues
