### ISSUE TITLE
Once role mapping is set, it can't be undone.

### ISSUE THREAD

**Issue by kabalin** [Panopto/Moodle-2.0-plugin-for-Panopto#35]
It seems not possible to remove role mapping once it is set. The existing code skips updating the record if form values are empty (no mapping is set is set in the instance config form) (see https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/blob/master/block_panopto.php#L59-L64).

Issue is fixed in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/c8e5da45cd96e656c6b587038ab5fa0c7e418f7f

**Comment by Hiroshi-p** [comment]
Fixed by https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/4572d44f3a612dd83854b10cc27a4f24b8483b6e
