### ISSUE TITLE
Adding the block outside the course page should be disabled.

### ISSUE THREAD

**Issue by kabalin** [Panopto/Moodle-2.0-plugin-for-Panopto#37]
Currently the block can be added nearly anywhere in Moodle, it makes little sense since the block relies on course data and enrolments. Adding it to "Site page" or any admin page will result in fatal error on attempt to "provision the course".

In theory it is possible to add it within the mod, that will probably not cause error, but will display a duplicated the data of any panopto block within the same course (since there is only one configuration record per course in block_panopto_foldermap). This is inconsistent with the idea others mod-enabled blocks are following that allows a unique content if block is within the mod. Also, it is not clear what to do on block deletion within mod, if #36 is applied, it would need to determine that other blocks exist in course and skip cleanup on deletion.

So for current state, adding the block outside the course page should be disabled. More work is needed if one wish to have possibility to add it somewhere else in Moodle.

Issue is fixed in https://github.com/lucisgit/Moodle-2.0-Plugin-for-Panopto/commit/0beda49ed71bb386363e217557a15ddc4fde01b0

**Comment by Hiroshi-p** [comment]
Fixed by https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/4572d44f3a612dd83854b10cc27a4f24b8483b6e
