### ISSUE TITLE
Adding teachers as students

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Moodle-2.0-plugin-for-Panopto#40]
Hi ,
Just pulled the recent changed from the master branch and unfortunately its not working for me!
I've added two teachers to a course with Panopto block enabled and when i provision it ( ideally this should happen on its own) it tries to add the teachers as students when provisioning and complains that there are no instructors.

![image](https://cloud.githubusercontent.com/assets/2855029/6639995/4c64d894-c98c-11e4-877b-9181f505aea0.png)

![image](https://cloud.githubusercontent.com/assets/2855029/6640057/d683b720-c98c-11e4-8ab0-6c331983ecf6.png)

where ha386 and esslw are teachers and not students

Hittesh

**Comment by Panopto** [comment]
Hello Hittesh,

Just so I have all the right details -- Is this the change that happened on March 5th in the main branch or the change yesterday to the active dev branch? I would like to see if we can repro this in house.

Jenn

**Comment by kabalin** [comment]
@hitteshahuja, by default "block/panopto:provision_asteacher" capability is not given to Teacher role in Moodle. While provisining the course, the list of users who should become "Creator" is build using "block/panopto:provision_asteacher" capability, therefore your teachers do not became "Creators" in Panopto unless your teacher role in Moodle has this capability granted. Same applies when you change the role of enrolled user in the course that has been provisioned already, unless Teacher role has required capability, no change will be made in role of corresponsing user in remote Panopto folder (i.e. your teacher will not became a Creator).

**Comment by hitteshahuja** [comment]
@kabalin  That explains it. Looks like this capability was not in the previous versions of Panopto .I guess it would be safe to assume to most moodle installations would want 'Teacher' roles to be 'publishers' for this purpse and hence add it to the access.db file ?

**Comment by kabalin** [comment]
@hitteshahuja The capability to provision the course was given to Teacher role by default before the patch https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/97755657b52a954d6c513fe5fcdbfe35b3d04e1a#diff-cce5aa4177e1c8221aed06f44b1e49b3. I think the original reason of removing it was adding the feature to configure roles on per block basis, e.g. everyone is viewer by default unless someone wish to grant some specific roles "Creator" rights. May be @PeterLancaster can shed more light on it? 

Personally I do not like the ability to configure roles on per block instance basis, there is a risk of some uncontrolled privilege escalation, as someone who can edit block can effectively make anyone enrolled in the course to become "Creator" in Panopto folder, and this could be something that Panopto admins do not expect ordinary teacher to do.

**Comment by hitteshahuja** [comment]
+1 to @kabalin  suggestion to not have capabilities defined on per block basis.

**Comment by Panopto** [comment]
I created a new internal feature request to capture this conversation. Does this sound like a good recap?

Add these two things to the Moodle block admin settings page:
 1. A way to configure the default role mappings for courses.
 2. A way to disable editing the role mappings on a per-course basis

Jenn

**Comment by kabalin** [comment]
@Panopto:
1. This functionality is already there, it is called Moodle Roles - by assigning certain capabilites to given roles one can change default Panopto role mappings for the course. The issue was that by default (after plugin installation), no role has capability to "provision_asteacher" any more, which caused confusion. This should be mentioned in documentation at least.

2. I am sure you meant per-block basis, yes, that would be good to have a possbility to disable it.

**Comment by kabalin** [comment]
OK, just realised that I completely forgot that Moodle allows changing permission at any context level, which means that per-block role mapping in Panopto block is not needed (it is a shame, I am sure the person who committed the patch spent a lot of time developing it).

Basically, to do per-block roles "mapping", all you need is to edit the block, then click Permissions at block administration menu on the left. You may give certain Panopto block rights to any role applicable in this context - all roles changes will affect only current block instance and will be used correctly during provisioning or course role changes.
![block_panopto-permissions](https://cloud.githubusercontent.com/assets/329780/6750114/fd9db43e-ceee-11e4-9dec-807883221655.png)

**Comment by kabalin** [comment]
Could you please state which commit/release fixes this? Thanks.

**Comment by Panopto** [comment]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/f0aab3bd9fd30d3c8055b7cc72e7b9bf7e7a7753
