### ISSUE TITLE
Role mapping is updated every time the block content is loaded

### ISSUE THREAD

**Issue by kabalin** [Panopto/Moodle-2.0-plugin-for-Panopto#42]
It seems an overhead updating roles mapping on every page where block is displayed ([see block_panopto->get_content()](https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/blob/master/block_panopto.php#L137:L140)), it needs to be done only once when mapping configuration is edited and saved.

**Comment by jmalmsten-panopto** [comment]
This should be taken care of in 2017101904, let me know if you have any other issues.
