### ISSUE TITLE
rollingsync does not adhere to roles when adding them to Panopto

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Moodle-2.0-plugin-for-Panopto#43]
When adding ,say ,a teacher manually to a course using the Manual Enrollment plugin teachers are by default added as viewers to Panopto. 

![image](https://cloud.githubusercontent.com/assets/2855029/7679427/7d9984b8-fd54-11e4-86bc-f2e04bdb1928.png)

![image](https://cloud.githubusercontent.com/assets/2855029/7679442/a065d1d6-fd54-11e4-82cc-1d2d479653e1.png)

Only after I provision the course the right role is passed through to panopto : 

![image](https://cloud.githubusercontent.com/assets/2855029/7679468/df35cf10-fd54-11e4-873c-a0df3d037498.png)

**Comment by nrparmar** [comment]
I've been working alongside Hittesh on testing this functionality, so am up to speed on the conversation. For completeness, I should add that unenrolling Georgina from the Moodle course also unenrols her from the Panopto folder immediately (as expected).

**Comment by Panopto** [comment]
Hi Hittesh,

Thank you for bringing up this issue. Having looked into your problem, I found that default roles were not being set properly the first time a course was provisioned, meaning that until role mappings were changed manually, all moodle roles mapped to the viewer role in Panopto. I made a change [here](https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/a61280e94fb5c988b784da9938c6c5916942e745) that should fix this problem. 
If you download the latest version of the block and upgrade your moodle server with it, your problem should be resolved.

**Comment by Panopto** [comment]
I should note that this fix will only apply for newly provisioned or reprovisioned courses. For courses that have been previously provisioned, you will need to set the custom role mappings manually by going to the configuration settings for the Panopto block on your course, opening the 'Change Panopto Role Mappings' tab, and selecting which moodle roles you would like to map to which Panopto roles. After doing this and saving, any users added to a course should have their proper role in Panopto.

**Comment by nrparmar** [comment]
Thank you for acting on this so quickly. I'll ask Hittesh to install the latest version of the Panopto block on our test server, so I that I can confirm whether or not the issue has been resolved at our end.
