### ISSUE TITLE
Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by agrowe** [Panopto/Moodle-2.0-plugin-for-Panopto#49]
Hi, in the recent changes made to the plugin, especially `version.php` being called in `settings.php`, it is now generating this error message

````
Warning: Creating default object from empty value in /var/www/studysmartstage/acpe/blocks/panopto/version.php on line 30
````

The `$plugin` variable in `version.php` is now not being created properly.

I have added the below line to get this error to clear in `version.php`

````
//Current internal version number.
$internalversion =2015111901;
$plugin = (isset($plugin) ? $plugin : new stdClass());
````

Thanks

**Comment by Hiroshi-p** [comment]
Thank you for reporting this. We track this our internal work item 41908 and will fix it.

**Comment by jmalmsten-panopto** [comment]
The fix posted here is now being used in the code.
