### ISSUE TITLE
Localize the link "Provision Course"

### ISSUE THREAD

**Issue by jackdaniels79** [Panopto/Moodle-2.0-plugin-for-Panopto#51]
In block_panopto.php, please use get_string for the link displayed in the block when the course have not been sync with Panopto yet. Right now, "Provision Course" is hardcoded in the function get_content:

`#152: $this->content->text = get_string('unprovisioned', 'block_panopto') . "
<br/><br/>
 <a href='$CFG->wwwroot/blocks/panopto/provision_course_internal.php?id=$COURSE->id'>Provision Course</a>";`

**Comment by jmalmsten-panopto** [comment]
This line is no longer in the code base and all language strings should be using get_string now.
