### ISSUE TITLE
Future deprecated message: PHP 7

### ISSUE THREAD

**Issue by sharpchi** [Panopto/Moodle-2.0-plugin-for-Panopto#52]
I'm currently testing Moodle in PHP7.0 and the logs are showing up the following message:

 ```PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; panopto_soap_client has a deprecated constructor in /var/www/html/blocks/panopto/lib/panopto_soap_client.php on line 32```

Looks like the function `panopto_soap_client` needs to be changed, perhaps `panopto_soap_client_init`?

**Plugin version:** 2015051802
thanks

**Comment by merrill-oakland** [comment]
No, it needs to be changed to __construct, or you need to add something like:
```php
public function __construct($servername, $apiuseruserkey, $apiuserauthcode) {
    self::panopto_soap_client($servername, $apiuseruserkey, $apiuserauthcode);
}
```

**Comment by panoptoadmin** [comment]
We took this pull request and I assume this resolves the issue: https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/pull/64
