### ISSUE TITLE
Class 'soap_client_with_timeout' not found

### ISSUE THREAD

**Issue by sleitao** [Panopto/Moodle-2.0-plugin-for-Panopto#53]
We are having the following issue:

Class 'soap_client_with_timeout' not found in /var/www/html/moodle2015/blocks/panopto/lib/panopto_soap_client.php on line 30

include ("/soap_client_with_timeout.php"); 
???

**Comment by hitteshahuja** [comment]
this commit should fix it : https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/f9e85f3976bbbe9590b8f66fa18f02fe0b3d8587

**Comment by Panopto** [comment]
hitteshahuja is correct, this problem should be resolved by using the latest version of the block.

**Comment by hitteshahuja** [comment]
Having said that ( sorry being devils's advocate!) it gets overwritten by this : https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/4269302741f44280c28316535084b6fa31af85b0#diff-3d8553b650c1f821f3ffcfe68dd96b6aR29

**Comment by Panopto** [comment]
Ah, thank you! Sorry that that was overlooked. This is now fixed again with commit at https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/bf1a131cb5f64a702e8b3a546419165bcd82d1b5, and the issue should be fixed by upgrading to the latest block

**Comment by sleitao** [comment]
Thanks.

**Comment by zakmussig** [comment]
I created a GitHub account just to post about this and you already fixed it! Thanks! :) I just removed the "/" in front of "soap_client_with_timeout.php", but I'll update again to the latest release.

**Comment by Hiroshi-p** [comment]
Since this was fixed, I am closing this entry.
