### ISSUE TITLE
Including version.php in settings.php causes issues

### ISSUE THREAD

**Issue by agrowe** [Panopto/Moodle-2.0-plugin-for-Panopto#56]
Hi Panopto,
Previously when you changed to used $internalversion in the version.php file, there was an issue where $plugin was not defined properly and caused errors under developer debugging. That was resolved by the if/else for setting $plugin to $plugin or as a new stdClass.

I am now seeing issues where on every tool/plugin, we are getting the same error but for their plugins instead. Once I removed the call to version.php in the settings.php file, and hard coded the $internalversion in settings.php the error was resolved.

Thanks
Alex

**Comment by Hiroshi-p** [comment]
We internally tested plug-in 2016081900 Release with Moodle 3.1 and this problem did not repro.
It is assumed to be fixed by one of commits between the issue was opened and right now.
Please feel free to reopen this if anyone sees this problem with latest Moodle + latest plug-in.
