### ISSUE TITLE
PHP style comments in style.css

### ISSUE THREAD

**Issue by agrowe** [Panopto/Moodle-2.0-plugin-for-Panopto#57]
Hi Panopto

The style.css file has PHP comments at the top. I have removed them in my local version, but would need to be changed in your version.

Thanks
Alex

**Comment by Hiroshi-p** [comment]
Thank you for reporting this. We track this our internal work item 41908 and will fix it.

**Comment by Hiroshi-p** [comment]
@agrowe 
I am sorry that I overlooked that you actually submitted the pull request.
I now merged your change.
