### ISSUE TITLE
permissions over "Viewer" level are not removed

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#61]
On user un-enroll, if the corresponding Panopto role is above "Viewer" the permissions are not removed on the Panopto side.  This is due to the fact that the role of an unenrolled user can not be determined.  This is fixed in https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/pull/60

**Comment by Syxton** [comment]
@Hiroshi-p Ok, so after getting back in the code, here is what is happening.
By default, the get_role_from_context() which looks to Moodle to decide what role the user has that get's removed will report "Viewer".  When a user is removed, their role is removed in Moodle and THEN the panopto tasks are executed, which means that by the time the get_role_from_context() function is ran, the role no longer exists in Moodle to decide which Panopto permission to remove, so it defaults to "Viewer". 

My patch ensures that a user will lose their permissions in a course if their enrollment is removed, however an unintended issue may arise if a user has more than one enrollment method giving them access to a course.  For instance, I could be enrolled as a "Student" by an external database, but given a "Teacher" role manually.  If no fix is applied and the Teacher role were removed, the user would lose their Teacher role in Moodle but keep their expanded role in Panopto.  If my patch were applied the user would lose their Teacher role in Moodle, and lose ALL rights in Panopto.  No neither version is perfect.  This code needs executed with prior knowledge of the role that has been removed.

**Comment by Hiroshi-p** [comment]
@Syxton 
Thank you for the explanation.
I understand that the fundamental problem is that we do not distinguish between viewer access and 'no' access. 
I think you may continue to apply your patch safely to your own installation with the assumption that multiple role assignment is not used in your system. However, I am hesitate to apply this patch for everyone.
If you find the better logic to distinguish viewer and no access, that's great.
But I suppose it's beyond your interest or available time.
In that case, we will investigate the ultimate fix in the near future.

**Comment by Syxton** [comment]
@Hiroshi-p After a brief look at documentation, it seems that what should happen is the Panopto events should be observers instead and use the add_record_snapshot() feature to keep the data in a cache that can be used after the fact.

**Comment by Syxton** [comment]
@Hiroshi-p This method removes all Panopto roles and then re-adds any existing roles.  Just a thought.

**Comment by Hiroshi-p** [comment]
Panopto internal track number 42700

**Comment by jmalmsten-panopto** [comment]
Hey, 

We just did a major update that should take care of this. Let me know if you still experience this issue.
