### ISSUE TITLE
permissions are not changed on enrollment suspension / reactivation

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#62]
Fixed in https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/pull/60

**Comment by Syxton** [comment]
Could you look at https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/pull/60/commits/9b7bff28d825ebdff23ae2aa71aff19122c948bb and see if this could be used.  Thanks!

**Comment by Hiroshi-p** [comment]
Thank you for suggesting the fix, @Syxton 

We looked at this specific commit  9b7bff2   (but not entire pull request #60 ). We understand that this resolves your problem. However, this seems to have side effect to some other users who have the case that a single Moodle user has multiple roles and one of these roles may be stripped individually. Therefore, this commit may not be taken as-is to our master branch.

Assuming the issue you want to solve here is what happens with our released plug-in (not specific to your cron job), could you open a support ticket to our support team and make us understand the exact scenario and get the local repro on our side? (Or if you already did so, could you tell me ticket number?)

Thanks again for your help and contribution to our product.

**Comment by Syxton** [comment]
This specific commit I am concerned about the sync of roles that become suspended / reactivated.

**Comment by Syxton** [comment]
#72

**Comment by Syxton** [comment]
@Hiroshi-p Here is the activation / deactivation event code

**Comment by Hiroshi-p** [comment]
Panopto internal track number 42729
