### ISSUE TITLE
When using the editor chooser, the current course is not always selected.

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#63]
As an admin, I have more than 5000 course folders that show up.  Most of the time, the correct folder is not selected in the list, and it takes a lot of time to find the correct one.

**Comment by Hiroshi-p** [comment]
Thank you for reporting this. We track this as our internal work item 41914 and will fix it.

**Comment by jmalmsten-panopto** [comment]
Closing, this is an issue with the Atto/Tinymce plugs ins that should be fixed in the release for those tonight.
