### ISSUE TITLE
User treatement is not the same

### ISSUE THREAD

**Issue by nmoller** [Panopto/Moodle-2.0-plugin-for-Panopto#65]
When you provision a course in Moodle, the first time when you link the course to the panopto's folder the mapping of the users is different from when you use the ad_hoc task:
**See the difference**:
[provisionning initially](http://nmoller.github.io/panopto/cp2.png)

[using the ad_hoc task after adding new users](http://nmoller.github.io/panopto/cp1.png)

The etu03 and prof02 are enrolled in the course after the initial linking happens in the second image.

I wonder why you use two different methods to do it... Could it be possible to unify the behaviour?

**Comment by Hiroshi-p** [comment]
Hi @nmoller,
Thank you for the report. Could you explain a little more about ad_hoc task?

**Comment by nmoller** [comment]
@Hiroshi-p 
The ad_hoc task is the script that is ran by the cron:
[https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/master/classes/task/update_user.php]

Can you tell me, please, what kind of explanation are we talking about?

**Comment by Hiroshi-p** [comment]
@nmoller,
I understand. Thank you for the clarificaiton. We'll look into it.

**Comment by Hiroshi-p** [comment]
Panopto internal tracking number 42664.

**Comment by jmalmsten-panopto** [comment]
This should be handled in the new update, closing.
