### ISSUE TITLE
Unprovisioned course causes error during event processing

### ISSUE THREAD

**Issue by merrill-oakland** [Panopto/Moodle-2.0-plugin-for-Panopto#66]
If you have a course with a block, but that is not provisioned, when the enrollment event fires a fatal error is triggered. This is because foldermap has a row for the course, but with no provisioning info, but the enrollment change processing doesn't recognize this state, and trues to connection to a blank hostname url (http:///Panopto/Services/ClientData.svc)

**Comment by Hiroshi-p** [comment]
We have tested this scenario with Moodle 3.1 server + Panopto latest plug-in, and we do not get the repro of this issue. Please feel free to reactivate if you still see this issue with this version. We may want to learn more detail repro step in this case.
