### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by sk-unikent** [Panopto/Moodle-2.0-plugin-for-Panopto#69]
Since we updated our server we keep getting this on cron run:
_An item with the same key has already been added._

Any idea why?

**Comment by Hiroshi-p** [comment]
@sk-unikent ,
Thank you for the report. We have not seen that failure in our testing. If this error message seems to break any functionality on your server, I would recommend to reach out our support team and investigate further.

**Comment by aspark21** [comment]
+1

**Comment by Hiroshi-p** [comment]
We tested this again, but we did not get repro. I understand this is related to upgrading the database and it may happen depending on the upgrade path. As the diagnosis requires the access to the database in general, please contact our support team if anyone else hits this error.
