### ISSUE TITLE
Blank shortname

### ISSUE THREAD

**Issue by elearningatbath** [Panopto/Moodle-2.0-plugin-for-Panopto#73]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/master/lib/panopto_data.php#L236

There could be courses on a Moodle site with no shortnames. For such courses, Panopto would provision them as "<NULL>:Course Long name" as folder names in Panopto. There should be an **if empty** check for $provisioninginfo->shortname and be replaced with a suitable value when pushing to the Panopto server. 

A possible suggestion could be using the initial letters of the long name in cases where no short name has been found. 

Something like :

``` php
if(empty($provisioninginfo->shortname ){
$provisioninginfo->shortname  = substr($provisioninginfo->longname,0, 5); 
}
```

Regards,
Hittesh

**Comment by jmalmsten-panopto** [comment]
Hi, 

I went ahead and implemented this fix into out future release, keep an eye out for it in the near future.
