### ISSUE TITLE
Code improvements to reduce PHP notices

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#75]
We are getting PHP Notices for Trying to get property of non-object in /exports/www/blocks/panopto/panopto_content.php 

Usually on lines like: 

if ($courseinfo->Access == "Error") {

and

if ($courseinfo->AudioPodcastURL){

**Comment by Syxton** [comment]
For the same reason, also getting:

PHP Warning:  Creating default object from empty value in 
/var/www/moodle/blocks/panopto/lib/panopto_data.php on line 236

**Comment by jmalmsten-panopto** [comment]
Hi,

Could you please let me know what version of the Panopto block you are using?

**Comment by Syxton** [comment]
We are having issues with 2016102400 but the issue exists in all versions.

**Comment by jmalmsten-panopto** [comment]
Looking at the code this would be happening when 

$panoptodata->get_course();

fails to return a panopto course, I can add some safety checks in the code to make sure you don't get these errors. Just curious did you perform any unique workflow on this course so I can try and narrow down the reproduction steps?

e.g. Did you maybe delete the course folder on the Panopto server or rename it, or maybe delete the course on moodle and make one with the same shortname/longname?
