### ISSUE TITLE
Javascript with comments and no linebreaks

### ISSUE THREAD

**Issue by merrill-oakland** [Panopto/Moodle-2.0-plugin-for-Panopto#76]
In block_panopto.php, get_content(), the javascript is loosely minified by removing linebreaks. The problem is that the JS also contains comments. In fact, the first script line is a comment, which completely disabled the code in the entire block. Either the comments need to be removed, or linebreaks need to be added after them.

**Comment by jmalmsten-panopto** [comment]
I went ahead and removed the quotes around them just to make them comments in the PHP, unless it is preferred they remain in the JS?

**Comment by merrill-oakland** [comment]
I find it a bit weird to have comment lines in the middle of a string concatenation in PHP, but it's a perfectly fine solution.
