### ISSUE TITLE
shortname not being sent to Panopto during provisioning

### ISSUE THREAD

**Issue by JohnnyCoughlin** [Panopto/Moodle-2.0-plugin-for-Panopto#78]
If I create a course in Moodle and then provision it by adding the Panopto block and clicking "Provision course", it creates a Panopto folder using just the course fullname. In previous iterations of the block (20160324), it would create a folder called "shortname:fullname". 

I believe this behavior is appearing because there's a typo on line 403 of lib/panopto_soap_client.php - That line make a call to get_xml_data_element, and the first parameter is set to shortname and it should be ShortName (note the difference in casing).

After changing that line in the code, I found that provisioning a new course created a folder on Panopto using the shortname:fullname, which is the expected behavior.

Note that I have a ticket open on this with Panopto support (case number 00331574).

**Comment by Hiroshi-p** [comment]
Thank you for the report. We will look into this. (TFS 43831)

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for catching this, the upcoming release of the panopto block will have this issue taken care of.

Keep an eye out for our next release.
