### ISSUE TITLE
Issue when block cannot communicate with Panopto server

### ISSUE THREAD

**Issue by dglloyd** [Panopto/Moodle-2.0-plugin-for-Panopto#8]
I realize this is an edge case, but today while performing maintenance on my Panopto server I received a call from our LMS team letting me know that any course that has the Panopto block enabled will hang for roughly 30 seconds while waiting for a time out.  Is it possible to make this an asynchronous call to avoid blocking the entire page load every time?  I realize that the Panopto Focus server being unavailable is and should be an extreme edge case, but feel that it is something that should be addressed regardless.

**Comment by Hiroshi-p** [comment]
@dglloyd 
I know this is stupidly late response.
I acknowledge that this problem still exists as of latest plug-in + Moodle 3.1.
We looked at if there is any quick fix, but nothing pops up given limited support of multithreading from PHP.
We continue to track this as internal issue and we may revisit if we have a chance to rearchitect this block.

**Comment by Hiroshi-p** [comment]
Internal tracking number 42914.

**Comment by hitteshahuja** [comment]
@Hiroshi-p  Is this not been fixed here https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/308b4b4e0d5accdf28f2279749595583ab577430 Or I havent understood OP's request ?

**Comment by Hiroshi-p** [comment]
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/308b4b4e0d5accdf28f2279749595583ab577430 changed how to load the plug-in. Unfortunately, that did not resolve the problem that course page with Panopto block becomes unresponsive when the block cannot reach Panopto server until timeout.

**Comment by jmalmsten-panopto** [comment]
Hey,

Super late reply but as of the more recent blocks we added a server health check that uses curl. If you still need this please and need assistance in setting it up please open a support ticket with Panopto.

Thanks,
Joe M
