### ISSUE TITLE
2016120900 Release auto provisioning of courses is resulting in an error

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#80]
Created a new course.  Waited a long time for the auto provisioning to occur.  When that didn't happen I clicked the link to provision the course.  Got an Error provisioning course response.

**Comment by Hiroshi-p** [comment]
Thank you for the report and I am sorry to hear that you hit the issue.
Could you open a ticket to our support team so that we may investigate together?

**Comment by jmalmsten-panopto** [comment]
Do you have any PHP error logs I could look at? I'm unable to repro any problems provisioning new courses on my test server. Maybe a DB upgrade problem.

**Comment by Syxton** [comment]
Previously our dev and prod were using the same identity provider.  I added one specifically for our dev system and now it works.  Was there a check added that would have caused this change?

**Comment by jmalmsten-panopto** [comment]
I don't believe we added any checks that would have affected this. I'm glad to hear it is working now. 

If you do have any further errors or concerns open a support ticket and add any logs you have in the ticket if needed, I'll be able to look at the issue better from there.
