### ISSUE TITLE
guest user when no authenticated Moodle user

### ISSUE THREAD

**Issue by woolardfa** [Panopto/Moodle-2.0-plugin-for-Panopto#92]
There is an issue when the event observers for role/enrolment are triggered when there is no authenticated user--i.e. a background process importing courses, and enrollments. The soap client then uses [instancename]\guest and creates the appropriate authcode, and authenticates. This guest user actually can invoke the methods to add other users to a course folder, and remove them as well, which is surprising. But when the guest user calls the 'GetCourse' method (from the ClientData.svc endpoint), an access error is returned. The code in panopto_data::get_provisioning_info() does not detect this failure, as the $mappedpanoptocourse is set (so isset fails), but with invalid data (default guid zeros for the folder id, etc.), and that in turn is passed back to the update_user task which calls the panopto_data::provision_course method.. the result of that is a SOAP Fault, specifically "Object reference not set to an instance of an object."

Have put in a support ticket on the Panopto site. Can dialog here or there, whichever is most convenient for you.

**Comment by jmalmsten-panopto** [comment]
Hey,

This issue should be taken care of, closing.
