### ISSUE TITLE
User making API call included in shared list when provisioning

### ISSUE THREAD

**Issue by woolardfa** [Panopto/Moodle-2.0-plugin-for-Panopto#93]
When the ProvisionCourse call is made on the ClientData.svc endpoint, the resulting course-folder includes the user who issued the call (with Can Create role). This ought not be the behavior considering: a) all of the users who should be in the shared list are provided in the ProvisioningInfo option (Publishers, Instructors, Students); and b) the user issuing the call might be the 'guest' user because there is no authenticated Moodle user in some cases, such as background enrollment processes--so in this case, there is an user [intancename]\guest with 'Can Create' role in all these folders.

**Comment by jmalmsten-panopto** [comment]
This should be taken care of in the new update, closing. Re-open if you experience this still.
