### ISSUE TITLE
Postgres Error when trying to provision a course with auto_add_admins enabled

### ISSUE THREAD

**Issue by katcher** [Panopto/Moodle-2.0-plugin-for-Panopto#96]
I have tried to upgrade our test 3.2 site with the most recent panopto plugin.  I tried to provision a course and had the following error:

Default exception handler: Error reading from database Debug: ERROR:  invalid input syntax for integer: "33339938,1,25258944,26155049,92390021,92398778,92403349,92414974,92414975,92429628,92429846"\nSELECT id, username, firstname, lastname, email FROM mdl_user WHERE id IN ($1)\n[array (\n  0 => '33339938,1,25258944,26155049,92390021,92398778,92403349,92414974,92414975,92429628,92429846',\n)]\r\nError code: dmlreadexception\n* line 479 of \\lib\\dml\\moodle_database.php: dml_read_exception thrown\n* line 242 of \\lib\\dml\\pgsql_native_moodle_database.php: call to moodle_database->query_end()\n* line 776 of \\lib\\dml\\pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()\n* line 492 of \\blocks\\panopto\\lib\\panopto_data.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 198 of \\blocks\\panopto\\provision_course.php: call to panopto_data->get_provisioning_info()\n, referer: https://xxx.yyy.ca/moodle-local/course/view.php?id=58796&sesskey=1wUxio6WeQ&bui_editid=629206

The issue appears to be resulting from the use of get_records_sql and the IN clause.

I have modified the code for panopto_data.php apprx line 482 to the following:

if (get_config('block_panopto', 'auto_add_admins')) {
            // All super admins should get access to all panopto courses as teachers, since they can all provision in the config page.
            $sql = "SELECT username, firstname, lastname, email " .
                   "FROM {user} " .
                   "WHERE";
			
            $siteAdmins =  explode(",",$CFG->siteadmins);
            list($usql, $params) = $DB->get_in_or_equal($siteAdmins);
            $sql .= " id $usql ";
            $superadmins = $DB->get_records_sql($sql, $params);

I beleive this solves the problem for postgres but I do not know if it will cause problems with other databases.

Please advise

Eric

**Comment by jmalmsten-panopto** [comment]
I don't think this code would cause any issues with other Database types, it works on my test environment (using mySQL). I'll include it for testing in our next update, so long as it passes testing you shouldn't have to modify this portion of the code afterwards. 

Thanks,
Joe
