### ISSUE TITLE
Soon-to-be deprecated constructors and Undefined property error with debug on latest 824a3e8

### ISSUE THREAD

**Issue by logan-reynolds** [Panopto/Moodle-2.0-plugin-for-Panopto#97]
When installing/testing with debug on M3.1/3.2 I'm seeing the following, which will become a problem for users as we go to higher versions of PHP7 - methods should be renamed to be different then their class:
`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; panopto_soap_client has a deprecated constructor in /var/www/html/MOODLE_31_STABLE/blocks/panopto/lib/panopto_soap_client.php on line 30`

Note I'm also seeing the followig minor notice that appears to indicate an undeclared/unset variable:
`Notice: Undefined property: stdClass::$block_panopto_server_number in /var/www/html/MOODLE_31_STABLE/blocks/panopto/settings.php on line 25`

**Comment by jmalmsten-panopto** [comment]
block_panopto_server_number should not be in the more recent versions of Panopto in the settings.php, please try upgrading and seeing if this issue persists. Closing. 

Thank you for bringing the php constructor issue to our attention, we will create an internal work item to track and deal with this.
